In [6]:
import pandas as pd
print(pd.__version__)
import numpy as np

3.0.5

LAOD AND EXPLORATION OF DATA

In [7]:
df=pd.read_csv("Property.csv",sep=';')

In [8]:
df.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent
0,347795,8,https://www.zameen.com/Property/lahore_model_t...,House,220000000,Model Town,Lahore,Punjab,31.483869,74.325686,0,6 Kanal,For Sale,0,07-17-2019,Real Biz International,Usama Khan
1,482892,48,https://www.zameen.com/Property/lahore_multan_...,House,40000000,Multan Road,Lahore,Punjab,31.431593,74.179980,5,1 Kanal,For Sale,5,10-06-2018,Khan Estate,mohsinkhan and B
2,555962,75,https://www.zameen.com/Property/eden_eden_aven...,House,9500000,Eden,Lahore,Punjab,31.499348,74.416959,0,9 Marla,For Sale,3,07-03-2019,Shahum Estate 2,"Babar Hameed, Raja Omar"
3,562843,3821,https://www.zameen.com/Property/gulberg_2_gulb...,House,125000000,Gulberg,Lahore,Punjab,31.522069,74.355512,7,1 Kanal,For Sale,8,04-04-2019,NaN,NaN
4,686990,3522,https://www.zameen.com/Property/allama_iqbal_t...,House,21000000,Allama Iqbal Town,Lahore,Punjab,31.506483,74.286017,5,11 Marla,For Sale,6,04-04-2019,NaN,NaN

In [9]:
df.shape

(191393, 17)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 191393 entries, 0 to 191392
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    191393 non-null  int64
 1   location_id    191393 non-null  int64
 2   page_url       191393 non-null  str
 3   property_type  191393 non-null  str
 4   price          191393 non-null  int64
 5   location       191393 non-null  str
 6   city           191393 non-null  str
 7   province_name  191393 non-null  str
 8   latitude       191393 non-null  float64
 9   longitude      191393 non-null  float64
 10  baths          191393 non-null  int64
 11  area           191393 non-null  str
 12  purpose        191393 non-null  str
 13  bedrooms       191393 non-null  int64
 14  date_added     191393 non-null  str
 15  agency         144014 non-null  str
 16  agent          144013 non-null  str
dtypes: float64(2), int64(5), str(10)
memory usage: 24.8 MB

In [11]:
df.describe()

,property_id,location_id,price,latitude,longitude,baths,bedrooms
count,1.913930e+05,191393.000000,1.913930e+05,191393.000000,191393.000000,191393.000000,191393.000000
mean,1.573170e+07,4224.580350,1.644655e+07,30.104593,71.572992,2.865956,3.171516
std,2.215249e+06,3719.125201,3.416412e+07,3.645941,3.080463,2.435332,1.952403
min,8.657500e+04,1.000000,0.000000e+00,11.052446,25.906027,0.000000,0.000000
25%,1.511867e+07,1057.000000,8.000000e+04,24.972287,67.152597,0.000000,2.000000
50%,1.676385e+07,3233.000000,7.300000e+06,31.463563,73.077743,3.000000,3.000000
75%,1.715282e+07,7182.000000,1.800000e+07,33.550869,74.228218,4.000000,4.000000
max,1.769386e+07,14246.000000,2.000000e+09,73.184088,80.161430,403.000000,68.000000

In [12]:
df.isnull().sum()

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           47379
agent            47380
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
print(df.columns)

Index(['property_id', 'location_id', 'page_url', 'property_type', 'price',
       'location', 'city', 'province_name', 'latitude', 'longitude', 'baths',
       'area', 'purpose', 'bedrooms', 'date_added', 'agency', 'agent'],
      dtype='str')

In [15]:
df['purpose'].value_counts()

purpose
For Sale    127018
For Rent     64375
Name: count, dtype: int64

In [16]:
df_sale=df[df['purpose']=='For Sale'].copy()
print(df_sale.shape)

(127018, 17)

In [17]:
df_sale['price'].describe()

count    1.270180e+05
mean     2.473577e+07
std      3.942639e+07
min      0.000000e+00
25%      7.500000e+06
50%      1.350000e+07
75%      2.600000e+07
max      2.000000e+09
Name: price, dtype: float64

In [18]:
df_sale["property_id"].duplicated().sum()

np.int64(0)

In [19]:
df_sale['area'].str.split().str[-1].value_counts()

area
Marla    107321
Kanal     19697
Name: count, dtype: int64

In [20]:
print((df_sale['price']==0).sum())

2

In [21]:
print("Lowest 3 prices:")
print(df_sale['price'].sort_values().head(3))
print("\nLargest 3 prices:")
print(df_sale['price'].sort_values().tail(3))

Lowest 3 prices:
140353    0
97464     0
186642    1
Name: price, dtype: int64

Largest 3 prices:
72863    1430000000
61464    1450000000
90714    2000000000
Name: price, dtype: int64

In [22]:
print(df_sale["price"].nsmallest(10))
print(df_sale["price"].nlargest(10))

97464     0
140353    0
10013     1
78718     1
165134    1
165404    1
170826    1
172059    1
177437    1
186642    1
Name: price, dtype: int64
90714     2000000000
61464     1450000000
72863     1430000000
81652     1350000000
15564     1270000000
39        1250000000
78587     1250000000
90        1200000000
58573     1000000000
101184    1000000000
Name: price, dtype: int64

In [23]:
print(df_sale["price"].quantile([0.001, 0.005, 0.01, 0.05]))

0.001     500034.0
0.005    1450000.0
0.010    1800000.0
0.050    3300000.0
Name: price, dtype: float64

In [24]:
print((df_sale["price"] < 100_000).sum())
print((df_sale["price"] < 500_000).sum())
print(df_sale[df_sale["price"] < 500_000][["price", "area", "city", "property_type"]].sample(10, random_state=42))

78
123
         price       area        city  property_type
117235  300000  2.5 Kanal   Islamabad          House
130617  400000  2.9 Marla      Lahore           Flat
130859   95000    1 Kanal      Lahore          House
170541   16000    5 Marla      Lahore          House
28527        8    1 Kanal     Karachi          House
127943   25000    9 Kanal      Lahore     Farm House
136730   25000   12 Marla  Rawalpindi  Upper Portion
175460   50000    5 Marla   Islamabad          House
125093  400000  2.9 Marla      Lahore          House
133424   23000   10 Marla      Lahore           Room

***Dropped price < 500,000: 123 rows, mostly rent-sized or typo prices (1, 8, 16,000 PKR)***

In [25]:
df_sale = df_sale[df_sale["price"] >= 500_000].copy()
print(df_sale.shape)

(126895, 17)

In [26]:
print(df_sale.loc[df_sale["price"].nlargest(3).index, ["price", "area", "city", "property_type"]])

            price        area     city property_type
90714  2000000000  19.2 Kanal   Lahore         House
61464  1450000000   6.1 Kanal  Karachi         House
72863  1430000000    13 Kanal   Lahore         House

In [30]:
num= df_sale['area'].str.split().str[0].str.replace(",","").astype(float)

factor = df_sale['area'].str.split().str[-1].map({"Marla": 1, "Kanal": 20}) 
df_sale['area_marla']= num* factor
df_sale['price_per_marla']=df_sale['price']/df_sale['area_marla']
print(df_sale['price_per_marla'].describe())
print(df_sale['price_per_marla'].quantile([0.001,0.01,0.5,0.99, 0.999]))

count    1.268950e+05
mean              inf
std               NaN
min      1.161305e+02
25%      1.500000e+06
50%      2.000000e+06
75%      2.675000e+06
max               inf
Name: price_per_marla, dtype: float64
0.001    8.526294e+04
0.010    4.625000e+05
0.500    2.000000e+06
0.990    7.500000e+06
0.999    1.357143e+07
Name: price_per_marla, dtype: float64

c:\Users\LENOVO\Desktop\Pakistan_real_estate_price_pridiction\venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

In [31]:
(df_sale["area_marla"]==0).sum()

np.int64(11)

In [32]:
df_sale=df_sale[df_sale['area_marla']>0].copy()

In [33]:
print(df_sale['price_per_marla'].describe())
print(df_sale['price_per_marla'].quantile([0.001,0.01,0.5,0.99, 0.999]))

count    1.268840e+05
mean     2.313672e+06
std      5.257733e+06
min      1.161305e+02
25%      1.500000e+06
50%      2.000000e+06
75%      2.675000e+06
max      1.500000e+09
Name: price_per_marla, dtype: float64
0.001    8.525971e+04
0.010    4.625000e+05
0.500    2.000000e+06
0.990    7.500000e+06
0.999    1.254179e+07
Name: price_per_marla, dtype: float64

In [ ]:
lo=df_sale.groupby('property_type')['price_per_marla'].transform(lambda s: s.quantile(0.01))
hi=df_sale.groupby('property_type')['price_per_marla'].transform(lambda s: s.quantile(0.99))
print(len(df_sale))
df_sale=df_sale[df_sale['price_per_marla'].between(lo,hi)].copy()
print(len(df_sale))
print(df_sale['price_per_marla'].describe())

126884
124356
count    1.243560e+05
mean     2.229696e+06
std      1.108272e+06
min      2.343750e+04
25%      1.500000e+06
50%      2.000000e+06
75%      2.656250e+06
max      7.812500e+06
Name: price_per_marla, dtype: float64

In [37]:
#baths
df_sale['baths_missing']=(df_sale['baths']==0).astype(int)
df_sale['baths']=df_sale['baths'].replace(0,np.nan)
df_sale['baths']= df_sale.groupby('property_type')['baths'].transform(lambda s: s.fillna(s.median()))

In [38]:
#baths
df_sale['bedsroom_missing']=(df_sale['bedrooms']==0).astype(int)
df_sale['bedrooms']=df_sale['bedrooms'].replace(0,np.nan)
df_sale['bedrooms']= df_sale.groupby('property_type')['bedrooms'].transform(lambda s: s.fillna(s.median()))

In [39]:
print(df_sale[["baths", "bedrooms"]].isna().sum())

baths       0
bedrooms    0
dtype: int64

In [40]:
col_to_drop=["page_url", "property_id", "location_id", "purpose", "province_name", "agency", "agent"]
df_sale=df_sale.drop(columns=col_to_drop)
print(df_sale.columns.tolist())

['property_type', 'price', 'location', 'city', 'latitude', 'longitude', 'baths', 'area', 'bedrooms', 'date_added', 'area_marla', 'price_per_marla', 'baths_missing', 'bedsroom_missing']